### ISSUE TITLE
oneOf without discriminator produces invalid spec

### ISSUE THREAD

**Issue by blakew** [faradayio/openapi-interfaces#10]
component schema:

```
    # We're going to add some other cases here and probably refactor this
    # later.
    ScopeInclude:
      oneOf:
        - required:
            - cohort_id
          type: object
          additionalProperties: false
          properties:
            cohort_id:
              type: string
              format: uuid
              example: 5bf9aa70-7bf1-4ef1-a131-8c84441be231
          description: A group of people, specified in one of a variety of ways.
```

This translates to 

```
    ScopeInclude:
      oneOf:
        - type: object
          required:
            - cohort_id
          properties:
            cohort_id:
              type: string
              example: 5bf9aa70-7bf1-4ef1-a131-8c84441be231
              format: uuid
          additionalProperties: false
          description: "A group of people, specified in one of a variety of ways."
      discriminator: ~
```

The `discriminator: ~` artifact is invalid spec and breaks tooling.

Discriminators are optional in OpenAPI - if they're not specified they shouldn't be emitted.
