### ISSUE TITLE
`title` not supported in interfaces

### ISSUE THREAD

**Issue by blakew** [faradayio/openapi-interfaces#11]
`title` is a property of component schemas, but there's no way to specify them with interfaces.

```
    TargetOptionsBigQuery:
      title: "bigquery options"
      description: "Bigquery replication target configuration options."
      members:
        connection_type:
          required: true
          initializable: true
          mutable: false
          schema:
            const: bigquery
            type: string
```

result:
```
ERROR: error: components.interfaces: expected interface: unknown field `title`, expected one of `emit`, `members`, `additionalMembers`, `description`, `example`
```
