### ISSUE TITLE
`type: object` not emitted in interfaces with oneOf and discriminator

### ISSUE THREAD

**Issue by blakew** [faradayio/openapi-interfaces#13]
`type: object` is required by AJV in component schemas with strict mode enabled.

```
    TargetOptions:
      oneOf:
        - $interface: "TargetOptionsBigQuery#SameAsInterface"
        - $interface: "TargetOptionsHostedApi#SameAsInterface"
        - $interface: "TargetOptionsHostedCsv#SameAsInterface"
        - $interface: "TargetOptionsRedshift#SameAsInterface"
        - $interface: "TargetOptionsS3Csv#SameAsInterface"
      discriminator:
        propertyName: connection_type
```

Does not emit a component schema with `type: object` set.

AJV error: 
```
strict mode: missing type "object" for keyword "discriminator" at "#/properties/options" (strictTypes)
```
