### ISSUE TITLE
`--avoid-type-null` removes all MergePatch properties

### ISSUE THREAD

**Issue by blakew** [faradayio/openapi-interfaces#15]
Input:

```
    Connection:
      $includes: "Resource"
      description: |
        Configuration for connecting data between Faraday and an external location.

        Connections are required when working with **replication targets**.
      members:
        resource_type:
          schema:
            example: connections
        id:
          initializable: false
          mutable: false
          schema:
            type: string
            format: uuid
            example: 5e0dfa56-2d52-4c06-a870-bc79c71e86a3
        name:
          required: true
          initializable: true
          mutable: true
          schema:
            type: string
            example: Snowflake AWS - Marketing
            description: A user-friendly name of the connection.
        options:
          required: true
          initializable: true
          mutable: true
          schema:
            $interface: "ConnectionOptions#SameAsInterface"
```

`MergePatch` output with `--avoid-type-null`:

```
    ConnectionMergePatch:
      type: object
      description: "A patch to `ConnectionPut` in JSON Merge Patch format (RFC 7396)."
```

Expected output:

```
    ConnectionMergePatch:
      type: object
      description: ...
      properties:
        name:
          type: string
          description: A user-friendly name of the connection.
          example: Snowflake AWS - Marketing
        options:
          $ref: "#/components/schemas/ConnectionOptionsMergePatch"
      additionalProperties: false
```
