### ISSUE TITLE
docs issue: clarify `initializable` parameter

### ISSUE THREAD

**Issue by blakew** [faradayio/openapi-interfaces#16]
The docs give all indication that `initializable` is a boolean but there's a comment that says 
```
        readonly:
          required: true
          # This can't be updated once the object is created.
          mutable: false
          # But we do allow this to be set at creation time.
          # If omitted, `initializable` defaults to the value
          # of `mutable.
          initializable: true
          schema:
            type: string
```

what does a value of `mutable` mean for this parameter? What's the interaction with the `mutable` parameter? Clarification appreciated.
