### ISSUE TITLE
Copy "description" into all generated interface variants

### ISSUE THREAD

**Issue by emk** [faradayio/openapi-interfaces#23]
From @blakew:

```yml
    ConnectionOptionsRedshiftPost:
      type: object
      # this is not currently copied over from the interface
      # into the POST, PUT, et al. derived components:
      description: INSERT REDSHIFT INSTRUCTIONS HERE
```
