### ISSUE TITLE
MergePatch types are null

### ISSUE THREAD

**Issue by blakew** [faradayio/openapi-interfaces#30]
Version: openapi-interfaces 0.3.0-rc.1

Input: 

```
    TargetOptionsHostedCsv:
      description: Hosted CSV target options
      discriminatorMemberName: type
      members:
        type:
          required: true
          initializable: true
          mutable: false
          schema:
            const: hosted_csv
            type: string
            description: The type of connection
        delimiter:
          required: false
          initializable: true
          mutable: true
          schema:
            type: string
            description: CSV delimiter
            pattern: ^[,;\t|]$
```

Output:

```
    TargetOptionsHostedCsvMergePatch:
      type: object
      required:
        - type
      properties:
        delimiter:
          type: ~
          oneOf:
            - type: string
              description: Pass this value to overwrite the existing value.
              title: Overwrite
              pattern: "^[,;\\t|]$"
            - type: "null"
              description: "Pass `null` to clear this field's existing value."
              title: Clear
          description: CSV delimiter
        type:
          type: string
          description: The type of connection
          const: hosted_csv
      additionalProperties: false
      description: "(Parameters used to PATCH the `TargetOptionsHostedCsv` type.)\n\nHosted CSV target options"
```

as you can see `type` is set to `~` above `oneOf`. I believe `type` here should just be ommitted (it's set correctly in `oneOf`). 

(I only observed this for MergePatch params.)
