### ISSUE TITLE
`discriminatorMemberName` isn't copied to *Put components

### ISSUE THREAD

**Issue by blakew** [faradayio/openapi-interfaces#31]
Input:
```
    TargetOptionsRedshift:
      description: AWS Redshift target options
      discriminatorMemberName: type
      members:
        type:
          required: true
          initializable: true
          mutable: false
          schema:
            const: redshift
            type: string
            description: The type of connection
        table_name:
          required: true
          initializable: true
          mutable: true
          schema:
            type: string
            description: Table name
            pattern: ^[_a-zA-Z][\$\w]{2,126}$
```
Output:
```
    TargetOptionsRedshiftPut:
      type: object
      required:
        - table_name
      properties:
        table_name:
          type: string
          description: Table name
          pattern: "^[_a-zA-Z][\\$\\w]{2,126}$"
      additionalProperties: false
      description: "(Parameters used to PUT a value of the `TargetOptionsRedshift` type.)\n\nAWS Redshift target options"
```
Expected `type` in the output
